# CI管道
kind: pipeline
type: kubernetes
name: sail-client

steps:
  - name: test
    image: golang:1.16.15
    environment:
      GOPROXY: https://goproxy.cn,direct
    volumes:
      - name: deps
        path: /go
    commands:
      - go get -d -t ./...
      - go test -v ./...
  - name: build
    image: golang:1.16.15-alpine3.15
    environment:
      GOPROXY: https://goproxy.cn,direct
    volumes:
      - name: deps
        path: /go
    commands:
      - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o service ./cmd/main.go
  - name: publishDocker
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      build_args:
        - serviceName=${DRONE_STAGE_NAME}
      dockerfile: ./deploy/Dockerfile
      context: .
      registry: ccr.ccs.tencentyun.com
      repo:  ccr.ccs.tencentyun.com/hyy-yu/${DRONE_REPO_NAME}
      purge: true
      tags:
        - ${DRONE_TAG}
    when:
      ref:
        - refs/tags/v*
volumes:
  - name: deps
    temp: {}
trigger:
  event:
    - push
    - tag