[sail]
etcd_endpoints = "127.0.0.1:2379,127.0.0.1:12379,127.0.0.1:22379"
etcd_username = "root"
etcd_password = "root"
project_key = "8a1b491062690963bd978fb8a6958371"
namespace = "test"
namespace_key = "NTUZNTNQNUKYEL4GP5SGVDV9LEYZAWBD"
configs = "cfg.properties,logger.json"
config_file_path = "."
log_level = "WARN"